# Generated by Django 5.0.2 on 2024-02-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('groups', models.ManyToManyField(to='learn.group')),
                ('products', models.ManyToManyField(to='learn.product')),
            ],
        ),
    ]
